# Generated by Django 5.0.4 on 2024-05-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='ARG_OF_PERICENTER',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='BSTAR',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='CLASSIFICATION_TYPE',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='ECCENTRICITY',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='ELEMENT_SET_NO',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='EPHEMERIS_TYPE',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='EPOCH',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='INCLINATION',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='MEAN_ANOMALY',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='MEAN_MOTION',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='MEAN_MOTION_DDOT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='MEAN_MOTION_DOT',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='NORAD_CAT_ID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='OBJECT_NAME',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='RA_OF_ASC_NODE',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='REV_AT_EPOCH',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='OBJECT_ID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
